version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:5.6
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - TZ=America/Sao_Paulo
    ports:
      - "3306:3306"    
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
