version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:5.6
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - TZ=America/Sao_Paulo
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", 'mysql --database=mysql --password=$$MYSQL_ROOT_PASSWORD --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B']
      interval: 30s
      timeout: 10s
      retries: 4      
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
